# Generated by Django 5.0 on 2023-12-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('destination_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_page', to='choose_your_own_adventure.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose_your_own_adventure.page')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='choose_your_own_adventure.page')),
            ],
        ),
    ]
