# Generated by Django 5.0 on 2024-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_your_own_adventure', '0002_alter_user_last_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_choice',
            field=models.CharField(blank=True, default='start', max_length=255, null=True),
        ),
    ]
