# Generated by Django 5.0.1 on 2024-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_your_own_adventure', '0003_alter_user_last_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
